import { Request, Response } from "express";
import { Sequelize, where } from "sequelize";
import bcrypt, { compare, hash } from "bcrypt";
import Interview from "../models/Interview.js";
import InterviewInstance from "../models/InterviewInstances.js";
import XLSX from "xlsx";
import multer from "multer";
import Admin from "../models/Admin.js";
import Student from "../models/student.js";
import College from "../models/College.js";
import Department from "../models/Department.js";
import InterviewToDepartment from "../models/InterviewToDepartments.js";
import InterviewExchange from "../models/InterviewExchanges.js";
import EvalMetrics from "../models/EvalMetrics.js";
import Resume from "../models/Resume.js";
import { deprecate } from "util";
